import Head from "next/head";
import Image from "next/image";
import AllSurah from "../components/AllSurah";
import Card from "../components/Card";
import Hero from "../components/Hero";
import Left from "../components/Left";
import Popular from "../components/Popular";
import SearchBar from "../components/SearchBar";
import styles from "../styles/Home.module.css";
import axios from "axios";
import { useDispatch, useSelector } from "react-redux";

export default function Home({ chapters }) {
  const bookmarkedSurah = useSelector(
    (state) => state.bookmark.bookmarkedSurah
  );
  const history = useSelector((state) => state.history.history);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Left />
        <div className={styles.right}>
          <SearchBar />
          <Hero />

          <Popular />
          <div className={styles.recent}>
            <div className={styles.heading}>Recently Bookmarked</div>
            <div className={styles.cards}>
              {bookmarkedSurah.slice(0, 6)?.map((item) => (
                <Card surah={item} bookmarkedSurah={bookmarkedSurah} />
              ))}
            </div>
          </div>
          <p></p>

          <div className={styles.recent}>
            <div className={styles.heading}>Recently Read</div>
            <div className={styles.cards}>
              {history.slice(0, 6)?.map((item) => (
                <Card surah={item} bookmarkedSurah={bookmarkedSurah} />
              ))}
            </div>
          </div>
          <AllSurah chapters={chapters} />
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getServerSideProps(context) {
  const { data } = await axios.get(
    "https://api.quran.com/api/v4/chapters?language=en"
  );
  console.log(data);
  return {
    props: { chapters: data.chapters }, // will be passed to the page component as props
  };
}
